online-mode=false
enforce-secure-profile=false
level-type=minecraft\:flat
generate-structures=false
spawn-protection=0
difficulty=peaceful
enable-rcon=true
rcon.password=smoke
rcon.port=25575
view-distance=4
simulation-distance=4
max-tick-time=-1
sync-chunk-writes=false
motd=opalikhovets smoke test
