org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod
mod_id=opalikhovets
mod_name=Opalikhovets
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.vinegretonline.opalikhovets
mod_authors=vinegretonline
mod_description=Adds a peaceful villager-like mob, the Opalikhovets, who takes photos of players with his phone.
